version: "3"
services:
  postgres_db_test:
    image: postgres
    container_name: postgres_db_test
    restart: always
    ports:
      - 4457:5432
    env_file:
      - back-end/.env.test

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_db_test
    env_file:
      - back-end/.env.test
    
  react_app:
    container_name: react_app
    build: ./front-end
    volumes:
      - build_react:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_db
      - node_app
      - react_app

volumes:
  build_react: